# Generated by Django 5.2.14 on 2026-06-07 13:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Category_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Category_description')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Product_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product_description')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Product_create_date')),
                ('up_date', models.DateTimeField(auto_now=True, verbose_name='Product_up_date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('product_img', models.URLField(max_length=255, verbose_name='Product_img')),
                ('quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Product_quantity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Product_category')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
