# Generated by Django 5.2.14 on 2026-06-08 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Product_quantity'),
            preserve_default=False,
        ),
    ]
